package x7;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import x7.*;
class Board{
	protected static JButton[][] board = new JButton[19][19];
	private JFrame frame = new JFrame("Xiangxi 1.0 Beta");
	private JPanel panel = new JPanel();
	private int x,y;
	Board(){
		panel.setLayout(new BorderLayout(21,21));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel("\u5317"));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[0][0]);
		panel.add(board[0][1]);
		panel.add(board[0][2]);
		panel.add(board[0][3]);
		panel.add(board[0][4]);
		panel.add(board[0][5]);
		panel.add(board[0][6]);
		panel.add(board[0][7]);
		panel.add(board[0][8]);
		panel.add(board[0][9]);
		panel.add(board[0][10]);
		panel.add(board[0][11]);
		panel.add(board[0][12]);
		panel.add(board[0][13]);
		panel.add(board[0][14]);
		panel.add(board[0][15]);
		panel.add(board[0][16]);
		panel.add(board[0][17]);
		panel.add(board[0][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[1][0]);
		panel.add(board[1][1]);
		panel.add(board[1][2]);
		panel.add(board[1][3]);
		panel.add(board[1][4]);
		panel.add(board[1][5]);
		panel.add(board[1][6]);
		panel.add(board[1][7]);
		panel.add(board[1][8]);
		panel.add(board[1][9]);
		panel.add(board[1][10]);
		panel.add(board[1][11]);
		panel.add(board[1][12]);
		panel.add(board[1][13]);
		panel.add(board[1][14]);
		panel.add(board[1][15]);
		panel.add(board[1][16]);
		panel.add(board[1][17]);
		panel.add(board[1][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[2][0]);
		panel.add(board[2][1]);
		panel.add(board[2][2]);
		panel.add(board[2][3]);
		panel.add(board[2][4]);
		panel.add(board[2][5]);
		panel.add(board[2][6]);
		panel.add(board[2][7]);
		panel.add(board[2][8]);
		panel.add(board[2][9]);
		panel.add(board[2][10]);
		panel.add(board[2][11]);
		panel.add(board[2][12]);
		panel.add(board[2][13]);
		panel.add(board[2][14]);
		panel.add(board[2][15]);
		panel.add(board[2][16]);
		panel.add(board[2][17]);
		panel.add(board[2][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[3][0]);
		panel.add(board[3][1]);
		panel.add(board[3][2]);
		panel.add(board[3][3]);
		panel.add(board[3][4]);
		panel.add(board[3][5]);
		panel.add(board[3][6]);
		panel.add(board[3][7]);
		panel.add(board[3][8]);
		panel.add(board[3][9]);
		panel.add(board[3][10]);
		panel.add(board[3][11]);
		panel.add(board[3][12]);
		panel.add(board[3][13]);
		panel.add(board[3][14]);
		panel.add(board[3][15]);
		panel.add(board[3][16]);
		panel.add(board[3][17]);
		panel.add(board[3][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[4][0]);
		panel.add(board[4][1]);
		panel.add(board[4][2]);
		panel.add(board[4][3]);
		panel.add(board[4][4]);
		panel.add(board[4][5]);
		panel.add(board[4][6]);
		panel.add(board[4][7]);
		panel.add(board[4][8]);
		panel.add(board[4][9]);
		panel.add(board[4][10]);
		panel.add(board[4][11]);
		panel.add(board[4][12]);
		panel.add(board[4][13]);
		panel.add(board[4][14]);
		panel.add(board[4][15]);
		panel.add(board[4][16]);
		panel.add(board[4][17]);
		panel.add(board[4][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[5][0]);
		panel.add(board[5][1]);
		panel.add(board[5][2]);
		panel.add(board[5][3]);
		panel.add(board[5][4]);
		panel.add(board[5][5]);
		panel.add(board[5][6]);
		panel.add(board[5][7]);
		panel.add(board[5][8]);
		panel.add(board[5][9]);
		panel.add(board[5][10]);
		panel.add(board[5][11]);
		panel.add(board[5][12]);
		panel.add(board[5][13]);
		panel.add(board[5][14]);
		panel.add(board[5][15]);
		panel.add(board[5][16]);
		panel.add(board[5][17]);
		panel.add(board[5][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[6][0]);
		panel.add(board[6][1]);
		panel.add(board[6][2]);
		panel.add(board[6][3]);
		panel.add(board[6][4]);
		panel.add(board[6][5]);
		panel.add(board[6][6]);
		panel.add(board[6][7]);
		panel.add(board[6][8]);
		panel.add(board[6][9]);
		panel.add(board[6][10]);
		panel.add(board[6][11]);
		panel.add(board[6][12]);
		panel.add(board[6][13]);
		panel.add(board[6][14]);
		panel.add(board[6][15]);
		panel.add(board[6][16]);
		panel.add(board[6][17]);
		panel.add(board[6][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[7][0]);
		panel.add(board[7][1]);
		panel.add(board[7][2]);
		panel.add(board[7][3]);
		panel.add(board[7][4]);
		panel.add(board[7][5]);
		panel.add(board[7][6]);
		panel.add(board[7][7]);
		panel.add(board[7][8]);
		panel.add(board[7][9]);
		panel.add(board[7][10]);
		panel.add(board[7][11]);
		panel.add(board[7][12]);
		panel.add(board[7][13]);
		panel.add(board[7][14]);
		panel.add(board[7][15]);
		panel.add(board[7][16]);
		panel.add(board[7][17]);
		panel.add(board[7][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[8][0]);
		panel.add(board[8][1]);
		panel.add(board[8][2]);
		panel.add(board[8][3]);
		panel.add(board[8][4]);
		panel.add(board[8][5]);
		panel.add(board[8][6]);
		panel.add(board[8][7]);
		panel.add(board[8][8]);
		panel.add(board[8][9]);
		panel.add(board[8][10]);
		panel.add(board[8][11]);
		panel.add(board[8][12]);
		panel.add(board[8][13]);
		panel.add(board[8][14]);
		panel.add(board[8][15]);
		panel.add(board[8][16]);
		panel.add(board[8][17]);
		panel.add(board[8][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel("\u897F"));
		panel.add(board[9][0]);
		panel.add(board[9][1]);
		panel.add(board[9][2]);
		panel.add(board[9][3]);
		panel.add(board[9][4]);
		panel.add(board[9][5]);
		panel.add(board[9][6]);
		panel.add(board[9][7]);
		panel.add(board[9][8]);
		panel.add(board[9][9]);
		panel.add(board[9][10]);
		panel.add(board[9][11]);
		panel.add(board[9][12]);
		panel.add(board[9][13]);
		panel.add(board[9][14]);
		panel.add(board[9][15]);
		panel.add(board[9][16]);
		panel.add(board[9][17]);
		panel.add(board[9][18]);
		panel.add(new JLabel("\u6771"));
		panel.add(new JLabel(""));
		panel.add(board[10][0]);
		panel.add(board[10][1]);
		panel.add(board[10][2]);
		panel.add(board[10][3]);
		panel.add(board[10][4]);
		panel.add(board[10][5]);
		panel.add(board[10][6]);
		panel.add(board[10][7]);
		panel.add(board[10][8]);
		panel.add(board[10][9]);
		panel.add(board[10][10]);
		panel.add(board[10][11]);
		panel.add(board[10][12]);
		panel.add(board[10][13]);
		panel.add(board[10][14]);
		panel.add(board[10][15]);
		panel.add(board[10][16]);
		panel.add(board[10][17]);
		panel.add(board[10][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[11][0]);
		panel.add(board[11][1]);
		panel.add(board[11][2]);
		panel.add(board[11][3]);
		panel.add(board[11][4]);
		panel.add(board[11][5]);
		panel.add(board[11][6]);
		panel.add(board[11][7]);
		panel.add(board[11][8]);
		panel.add(board[11][9]);
		panel.add(board[11][10]);
		panel.add(board[11][11]);
		panel.add(board[11][12]);
		panel.add(board[11][13]);
		panel.add(board[11][14]);
		panel.add(board[11][15]);
		panel.add(board[11][16]);
		panel.add(board[11][17]);
		panel.add(board[11][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[12][0]);
		panel.add(board[12][1]);
		panel.add(board[12][2]);
		panel.add(board[12][3]);
		panel.add(board[12][4]);
		panel.add(board[12][5]);
		panel.add(board[12][6]);
		panel.add(board[12][7]);
		panel.add(board[12][8]);
		panel.add(board[12][9]);
		panel.add(board[12][10]);
		panel.add(board[12][11]);
		panel.add(board[12][12]);
		panel.add(board[12][13]);
		panel.add(board[12][14]);
		panel.add(board[12][15]);
		panel.add(board[12][16]);
		panel.add(board[12][17]);
		panel.add(board[12][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[13][0]);
		panel.add(board[13][1]);
		panel.add(board[13][2]);
		panel.add(board[13][3]);
		panel.add(board[13][4]);
		panel.add(board[13][5]);
		panel.add(board[13][6]);
		panel.add(board[13][7]);
		panel.add(board[13][8]);
		panel.add(board[13][9]);
		panel.add(board[13][10]);
		panel.add(board[13][11]);
		panel.add(board[13][12]);
		panel.add(board[13][13]);
		panel.add(board[13][14]);
		panel.add(board[13][15]);
		panel.add(board[13][16]);
		panel.add(board[13][17]);
		panel.add(board[13][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[14][0]);
		panel.add(board[14][1]);
		panel.add(board[14][2]);
		panel.add(board[14][3]);
		panel.add(board[14][4]);
		panel.add(board[14][5]);
		panel.add(board[14][6]);
		panel.add(board[14][7]);
		panel.add(board[14][8]);
		panel.add(board[14][9]);
		panel.add(board[14][10]);
		panel.add(board[14][11]);
		panel.add(board[14][12]);
		panel.add(board[14][13]);
		panel.add(board[14][14]);
		panel.add(board[14][15]);
		panel.add(board[14][16]);
		panel.add(board[14][17]);
		panel.add(board[14][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[15][0]);
		panel.add(board[15][1]);
		panel.add(board[15][2]);
		panel.add(board[15][3]);
		panel.add(board[15][4]);
		panel.add(board[15][5]);
		panel.add(board[15][6]);
		panel.add(board[15][7]);
		panel.add(board[15][8]);
		panel.add(board[15][9]);
		panel.add(board[15][10]);
		panel.add(board[15][11]);
		panel.add(board[15][12]);
		panel.add(board[15][13]);
		panel.add(board[15][14]);
		panel.add(board[15][15]);
		panel.add(board[15][16]);
		panel.add(board[15][17]);
		panel.add(board[15][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[16][0]);
		panel.add(board[16][1]);
		panel.add(board[16][2]);
		panel.add(board[16][3]);
		panel.add(board[16][4]);
		panel.add(board[16][5]);
		panel.add(board[16][6]);
		panel.add(board[16][7]);
		panel.add(board[16][8]);
		panel.add(board[16][9]);
		panel.add(board[16][10]);
		panel.add(board[16][11]);
		panel.add(board[16][12]);
		panel.add(board[16][13]);
		panel.add(board[16][14]);
		panel.add(board[16][15]);
		panel.add(board[16][16]);
		panel.add(board[16][17]);
		panel.add(board[16][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[17][0]);
		panel.add(board[17][1]);
		panel.add(board[17][2]);
		panel.add(board[17][3]);
		panel.add(board[17][4]);
		panel.add(board[17][5]);
		panel.add(board[17][6]);
		panel.add(board[17][7]);
		panel.add(board[17][8]);
		panel.add(board[17][9]);
		panel.add(board[17][10]);
		panel.add(board[17][11]);
		panel.add(board[17][12]);
		panel.add(board[17][13]);
		panel.add(board[17][14]);
		panel.add(board[17][15]);
		panel.add(board[17][16]);
		panel.add(board[17][17]);
		panel.add(board[17][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(board[18][0]);
		panel.add(board[18][1]);
		panel.add(board[18][2]);
		panel.add(board[18][3]);
		panel.add(board[18][4]);
		panel.add(board[18][5]);
		panel.add(board[18][6]);
		panel.add(board[18][7]);
		panel.add(board[18][8]);
		panel.add(board[18][9]);
		panel.add(board[18][10]);
		panel.add(board[18][11]);
		panel.add(board[18][12]);
		panel.add(board[18][13]);
		panel.add(board[18][14]);
		panel.add(board[18][15]);
		panel.add(board[18][16]);
		panel.add(board[18][17]);
		panel.add(board[18][18]);
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel("\u5357"));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		panel.add(new JLabel(""));
		Reset.reset();
		frame.setVisible(true);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}
	public static void main(String[] args){
		new Board();
	}
}
